### PR TITLE
Tpetra: Replace LittleVector/LittleBlock with Kokkos::View

### PR DESCRIPTION
**Pull request by crtrott**
@trilinos/tpetra

This addresses issue #177

### CODE REVIEW

**Comment by mhoemmen** [comment]
Hm, this one has conflicts with Kyungjoo's pull request, which I already merged.  Let me look at the commits first.  Do they all build separately or should they be considered monolithic, as in, Tpetra and Ifpack2 won't build correctly without all of them?  If the latter, then we might want to consider squashing them into one commit.

**Comment by mhoemmen** [comment]
Performance question: I wrote Tpetra::Experimental::COPY in part because I wasn't sure whether Kokkos::deep_copy would incur too much overhead for small dense blocks and vectors.  Would it?

**Comment by mhoemmen** [comment]
Teuchos::Array has a getRawPtr() method; preferable to `&lclarray[0]` (ha, _I_ didn't write that, don't want to name names though ;-P ).

**Comment by mhoemmen** [comment]
Changes to packages/ifpack2/test/unit_tests/Ifpack2_UnitTestBlockRelaxation.cpp might not build with complex -- you assign result of ptr_on_device() (pointer to Kokkos::complex) to Scalar (pointer to std::complex) -- need reinterpret_cast or auto there.

**Comment by mhoemmen** [comment]
For the third commit: prefer reinterpret_cast to C-style casts

**Comment by mhoemmen** [comment]
For fourth commit: See above on reinterpret_cast and &lclarray[0].  Not your problem, though, esp. the latter.

**Comment by crtrott** [comment]
You should have applied mine first ;-). 
I can merge it tomorrow or so. I think all the casts are in place, at least I tested with complex.. We can change that to reinterpret cast if you want. I personally think that c-style casts are safer since they don't require binary equivalence, but in this case we probably need that anyway.

**Comment by mhoemmen** [comment]
> You should have applied mine first ;-).

My bad, sorry!  Wish i could get a whole day here of functional internet + no interruptions :(

> I personally think that c-style casts are safer since they don't require binary equivalence, but in this case we probably need that anyway.

For pointers we really need binary equivalence; Kokkos::complex works because we cross our fingers and hope that all std::complex implementations are packed (re, im) pairs.  It's cool, I just like C++ - style casts because you can grep for them.

**Comment by crtrott** [comment]
Opening a new one now

**Pull request closed without merging**
